### ISSUE TITLE
hypen in generated property name

### ISSUE THREAD

**Issue by snarky-puppy** [karlvr/openapi-generator-plus-generators#38]
I'm using an openapi spec with a hyphen in the property name, and I can't rename it to something sane.

```
components:
  schemas:
    SomeRequest:
      type: object
      properties:
        derp-derp:
          type: string
```

The generated code does not parse because hyphenated property name must be quoted.

```
export namespace Api {
  export interface SomeRequest {
    derp-derp: string;
  }
}
```

Is there a way I can rename the or quote the property? 

I have the templates copied into my project already so I can change them directly if needs be.

TIA
